baseURL = 'https://abramov.blog/'
languageCode = 'ru-ru'
title = 'Abramov blog'

[markup.highlight]
noClasses = false
guessSyntax = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[taxonomies]
tag = 'tags'
