baseURL = 'https://abramov.blog/'
locale = 'ru-RU'
title = 'Abramov blog'
contentDir = '../posts'

[markup.highlight]
noClasses = false

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[taxonomies]
tag = 'tags'

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
